// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDizrlmGGnMH2DCN2smUAvnPPopb3frnxk',
    appId: '1:191442204494:web:18557eb47c6fe5460d101f',
    messagingSenderId: '191442204494',
    projectId: 'categorizer-405012',
    authDomain: 'categorizer-405012.firebaseapp.com',
    storageBucket: 'categorizer-405012.appspot.com',
    measurementId: 'G-8Q13498T8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuLwkXl_F-0ABNFYYtjekFi3R2qXipyqg',
    appId: '1:191442204494:android:f12d7fbd221941f00d101f',
    messagingSenderId: '191442204494',
    projectId: 'categorizer-405012',
    storageBucket: 'categorizer-405012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRaz2y_5k1ibrdpMa8Z39sZ9q_ImJsgUs',
    appId: '1:191442204494:ios:b72d06159dfd98090d101f',
    messagingSenderId: '191442204494',
    projectId: 'categorizer-405012',
    storageBucket: 'categorizer-405012.appspot.com',
    iosBundleId: 'com.example.categorizer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRaz2y_5k1ibrdpMa8Z39sZ9q_ImJsgUs',
    appId: '1:191442204494:ios:e177b32cb0f0d83f0d101f',
    messagingSenderId: '191442204494',
    projectId: 'categorizer-405012',
    storageBucket: 'categorizer-405012.appspot.com',
    iosBundleId: 'com.example.categorizer2.RunnerTests',
  );
}
